### ISSUE TITLE
Syntax error near location  of c:\users\admini~1\appdata\local\temp\tmpozdd_hbincat\init.ini

### ISSUE THREAD

**Issue by NAPER010** [airbus-seclab/bincat#79]
I use Bincat v1.0rc which can support armv7/armv8/x86/powerpc. But when I loaded my test program which was powerpc, it showed error: INFO:bincat.plugin:EXCEPTION: Exceptions.Error("Syntax error near location (18, 22) of c:\\users\\admini~1\\appdata\\local\\temp\\tmpozdd_hbincat\\init.ini").
How to slove this problem? thanks!

**Comment by NAPER010** [comment]
log file for details:
###
 INFO:bincat.plugin:---- logfile ---------------
INFO:bincat.plugin:[INFO]  main: BinCAT version v0.9
INFO:bincat.plugin:[ABORT] main: Syntax error near location (18, 22) of c:\users\admini~1\appdata\local\temp\tmpozdd_hbincat\init.ini
INFO:bincat.plugin:Raised by primitive operation at file "utils/log.ml", line 157, characters 41-69
INFO:bincat.plugin:Called from file "main.ml", line 64, characters 8-105
INFO:bincat.plugin:Called from file "bincat.ml", line 25, characters 4-55
INFO:bincat.plugin:[EXCEPTION] main: Exception caught in main loop
INFO:bincat.plugin:Exceptions.Error("Syntax error near location (18, 22) of c:\\users\\admini~1\\appdata\\local\\temp\\tmpozdd_hbincat\\init.ini")
INFO:bincat.plugin:Raised at file "utils/log.ml", line 160, characters 4-32
INFO:bincat.plugin:Called from file "main.ml", line 64, characters 8-105
INFO:bincat.plugin:[STOP] nothing analyzed
INFO:bincat.plugin:====== end of logfile ======
###

**Comment by Lastpixl** [comment]
Hi!
Could you provide us with the init.ini file, so we can see what's wrong?
Thanks

**Comment by NAPER010** [comment]
[init.txt](https://github.com/airbus-seclab/bincat/files/2557911/init.txt)
This is the init.ini file.
Thanks for your help!

**Comment by Lastpixl** [comment]
Thanks!
I'm getting the following error with this init.txt:
```
Exceptions.Error("Syntax error near location (68, 5) of /home/x/Downloads/init.txt")
```
At line 68, I can see that you used
```
stack[0x1000*4099] = |00|?0xFF
```
It seems you were following the tutorial; be sure to use [the tutorial from branch v1.0rc](https://github.com/airbus-seclab/bincat/blob/v1.0rc/doc/tutorial.md). We have merged the `stack` region with the `mem` region, and `stack` is not supported anymore.

Cheers

**Comment by NAPER010** [comment]
> Thanks!
> I'm getting the following error with this init.txt:
> 
> ```
> Exceptions.Error("Syntax error near location (68, 5) of /home/x/Downloads/init.txt")
> ```
> At line 68, I can see that you used
> 
> ```
> stack[0x1000*4099] = |00|?0xFF
> ```
> It seems you were following the tutorial; be sure to use [the tutorial from branch v1.0rc](https://github.com/airbus-seclab/bincat/blob/v1.0rc/doc/tutorial.md). We have merged the `stack` region with the `mem` region, and `stack` is not supported anymore.
> 
> Cheers



> Thanks!
> I'm getting the following error with this init.txt:
> 
> ```
> Exceptions.Error("Syntax error near location (68, 5) of /home/x/Downloads/init.txt")
> ```
> At line 68, I can see that you used
> 
> ```
> stack[0x1000*4099] = |00|?0xFF
> ```
> It seems you were following the tutorial; be sure to use [the tutorial from branch v1.0rc](https://github.com/airbus-seclab/bincat/blob/v1.0rc/doc/tutorial.md). We have merged the `stack` region with the `mem` region, and `stack` is not supported anymore.
> 
> Cheers

Thank you very much!
But when i replcace the stack region with the mem region，the same problem still exists.
It showed error: 'INFO:bincat.plugin:EXCEPTION: Exceptions.Error("Syntax error near location (15, 15) of c:\\users\\admini~1\\appdata\\local\\temp\\tmpzheopubincat\\init.ini")'


[init.txt](https://github.com/airbus-seclab/bincat/files/2558059/init.txt)
This is the new init.ini file which i have changed.

**Comment by trou** [comment]
are you sure you are running the latest v1.0rc version ? 
Running bincat should display:
```
$ bincat
BinCAT v0.9-739-gfe2cfd12-dirty
```

**Comment by trou** [comment]
I'm closing the bug, please reopen it if you have more information.
